### ISSUE TITLE
Error on redirect 

### ISSUE THREAD

**Issue by peili** [scarvell/flashify#8]
I get the following error when using:
          req.flash('info', 'You are an awesome admin because you use flashify');
          return res.redirect("/");

/Users/peili/node_modules/meeting/node_modules/mongoose/lib/utils.js:413
        throw err;
              ^
TypeError: Object function (e) {
      var t, _ref;
      if ((t = this.indexOf(e)) > -1) {
        return ([].splice.apply(this, [t, t - t + 1].concat(_ref = [])), _ref);
      }
    } has no method 'forEach'
    at ServerResponse.res.redirect (/Users/peili/node_modules/meeting/node_modules/flashify/lib/flashify.js:80:32)
    at Promise.module.exports.app.post.passport.authenticate.failureRedirect (/Users/peili/node_modules/meeting/src/auth.js:202:22)

**Comment by romualdr** [comment]
Is this still a problem ?
